services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq-management
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge